### ISSUE TITLE
Question on tagging Σκυτοβραχΐων in book 3 scholia

### ISSUE THREAD

**Issue by brclar15** [homermultitext/archival-repairs#1]
in ana="3.40b" n="82", Dionysius has the nickname Σκυτοβραχΐων. If that nickname alone appeared without his name, we'd obviously tag it as his pers number. But when they both appear, do we tag both? 

"<persName n="urn:cite2:hmt:pers.r1:pers211">Διονύσιος</persName> φησιν ὁ
                           <persName n="urn:cite2:hmt:pers.r1:HELP">Σκυτοβραχΐων</persName>"

**Comment by neelsmith** [comment]
I think we tag Διονύσιος for sure.  The article really makes me want to leave Σκυτοβραχΐων as a common adjective.

**Comment by StephanieML** [comment]
I agree. We don't usually tag cases like that.
