### ISSUE TITLE
Question on tagging "Πριαμιδῶν" in ana="3.108a" n="179"

### ISSUE THREAD

**Issue by brclar15** [homermultitext/archival-repairs#2]
Am I to tag this as **all** the sons of Priam, or is there a way around that?

**Comment by neelsmith** [comment]
I think probably should treat this as a collective, and in at least some cases,  have done so already:   e.g., "Neleids" (pl.) have their own entry.

**Comment by StephanieML** [comment]
if it were only 1 or 2, we could, but Priam was far too busy for that to make sense here
